### ISSUE TITLE
HDFS数据集运行报错

### ISSUE THREAD

**Issue by Ricardo-Vv** [ZhongLIFR/Logs2Graph#1]
![image](https://github.com/ZhongLIFR/Logs2Graph/assets/52873978/9c53089e-2e5d-4918-8bb3-3c6ae21d5916)
您好，在运行main_HDFS.py时，会出现train_indices为空的情况，导致后面Dataloader.py第410行会出现train_dataset[0].num_features索引为空失败的原因，请问要怎么解决呢

**Comment by ZhongLIFR** [comment]
您好，我猜测应该是数据加载有问题，直接原因应该是数据里面满足data.y.item()==0的只有零条。你打印一下中间结果，应该能排查出bug。

**Comment by Ricardo-Vv** [comment]
是的，我发现在main_HDFS.py中第72行读取HDFS数据集时，文件HDFS_graph_labels.txt只有15个label且没有为0的label，是不是数据预处理或者数据集出了问题呢。好像hadoop没有这个问题。
![image](https://github.com/ZhongLIFR/Logs2Graph/assets/52873978/2f64965f-5e2d-4802-8c03-c0d07a47d319)

**Comment by Ricardo-Vv** [comment]
重新运行图生成文件后，一切都解决了，感谢你的帮助~
