### ISSUE TITLE
bdist_wheel did not run successfully.

### ISSUE THREAD

**Issue by khadija267** [ZhongLIFR/Logs2Graph#3]
I got this error while running on colab:

Building wheels for collected packages: torch_scatter
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for torch_scatter (setup.py) ... error
  ERROR: Failed building wheel for torch_scatter
  Running setup.py clean for torch_scatter
Failed to build torch_scatter
ERROR: Could not build wheels for torch_scatter, which is required to install pyproject.toml-based projects

**Comment by khadija267** [comment]
This works: 
!pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.1+cu101.html

With these versions:

!pip install matplotlib==3.6.0
!pip install networkx==2.6.3
!pip install numpy==1.23.0
!pip install pandas==1.5.0
!pip install scikit_learn==1.2.2
!pip install scipy==1.10.1
!pip install torch==2.1.0
!pip install torch_geometric==2.2.0
!pip install tqdm==4.50.2

**Comment by ZhongLIFR** [comment]
Hi,
It is nice to see that you have solved the issues:) So I will close this issue
